algolia/doc-code-samples

React InstantSearch/routing-seo-friendly/src/App.js
@coreyching reported that the react seo-friendly example did not work https://nw5jpkjkj4.codesandbox.io/
1. open https://nw5jpkjkj4.codesandbox.io/
2. In the brands refinement list, click on HP
**Observed**: state is applied than "rolledback", url is not updated
**Expected**: state is applied, url is updated 
It should be fixed here: https://codesandbox.io/s/pmmzw7n830
=> React: fix createUrl function in seo-friendly example

React InstantSearch/routing-seo-friendly/package.json, React InstantSearch/routing-seo-friendly/public/index.html, React InstantSearch/routing-seo-friendly/public/manifest.json, React InstantSearch/routing-seo-friendly/src/App.css, React InstantSearch/routing-seo-friendly/src/App.js, React InstantSearch/routing-seo-friendly/yarn.lock
This updates the SEO-friendly routing React InstantSearch example with a more appropriate URL schema. This example will be the base of the new [Routing URLs](https://www.algolia.com/doc/guides/building-search-ui/going-further/routing-urls/react/) guide.
```sh
https://website.com/?menu[categories]=Cell Phones&refinementList[brand][0]=Apple&refinementList[brand][1]=Samsung&page=2&query=galaxy
```
```sh
https://website.com/Cell+Phones/?query=galaxy&page=2&brands=Apple&brands=Samsung
```
[See preview →](https://codesandbox.io/s/github/algolia/doc-code-samples/tree/react-seo-routing/React+InstantSearch/routing-seo-friendly)
=> feat(react): update SEO-friendly routing example

Angular InstantSearch/routing-angular-router/src/app/index/index.component.html, Angular InstantSearch/routing-full-url/src/app/index/index.component.html, Angular InstantSearch/routing-state-mapping/src/app/index/index.component.html
This PR uses the `routerLink` directive rather than `href`. 
It prevents the browser to completely refresh the page when we transition from one page to another.
=> fix: use router-link

InstantSearch.js/query-suggestions/index.html, InstantSearch.js/query-suggestions/package.json, InstantSearch.js/query-suggestions/src/app.css, InstantSearch.js/query-suggestions/src/app.js, InstantSearch.js/query-suggestions/src/index.css, InstantSearch.js/query-suggestions/yarn.lock
This updates the [*Query Suggestions* guide](https://www.algolia.com/doc/guides/building-search-ui/resources/ui-and-ux-patterns/in-depth/query-suggestions/js/) to Autocomplete v1.
I use a child index that takes care of the Query Suggestions index. This index is "detached" in the sense that it doesn't refine the main index query on every key stroke, but only on select and on submit via the [`setUiState`](https://www.algolia.com/doc/api-reference/widgets/instantsearch/js/#widget-param-setuistate) API. In addition to refining the search, it applies the categories from the selected item. On submit, we reset all categories.
| Before | After |
|---|---|
| [Demo →](https://codesandbox.io/s/github/algolia/doc-code-samples/blob/master/InstantSearch.js/query-suggestions) | [Demo …
=> feat(autocomplete): update Query Suggestions to Autocomplete v1

Vue InstantSearch/routing-vue-router/src/views/Home.vue
This PR updates the wrong index name (`demo_ecommerce` -> `instant_search`).
The vue-router example was broken.
* before: https://codesandbox.io/s/github/algolia/doc-code-samples/tree/master/Vue%20InstantSearch/routing-vue-router
* after: https://codesandbox.io/s/github/algolia/doc-code-samples/tree/fix/vue-router/Vue%20InstantSearch/routing-vue-router?file=/src/main.js
=> fix(vue): update the wrong index name in the example

Angular InstantSearch/conditional-request/src/app/app.component.ts, InstantSearch.js/conditional-request/src/app.js, React InstantSearch/conditional-request/src/App.js, Vue InstantSearch/conditional-request/src/App.vue
This PR spreads `algoliaClient` in `searchClient` in conditional requests examples.
We're mocking `searchClient` but only expose `search` function, so it can lead to unexpected error due to lack of other properties or methods.
In the recent support ticket, insights middleware failed to get appId and apiKey from the searchClient. So we'd better spread the algoliaClient to the searchClient.
rel: https://github.com/algolia/doc/pull/5697
=> fix(conditional-request): spread algoliaClient

.circleci/config.yml
To upgrade the code samples to their Angular 12 version, we need to use node > 12.
Added node 14 for building angular projects.
I'm not sure yet all examples can build on node 14 before they migrated, let's see if it does :)
=> chore(node14): update node version for angular projects

Angular InstantSearch/getting-started/tsconfig.json
The current sandbow is broken because it can't find the default import for `algoliasearch/lite`.
This fixes it by setting `esModuleInterop` to `true`.
Note that this shouldn't be needed as per [this fix](https://github.com/algolia/algoliasearch-client-javascript/issues/1000). The sandbox uses [recent versions of the client and of TypeScript](https://github.com/algolia/doc-code-samples/blob/master/Angular%20InstantSearch/getting-started/package.json#L21-L40), so there might be something to investigate.
=> fix(angular-instantsearch): fix ES module interoperability

React InstantSearch/routing-basic/package.json, React InstantSearch/routing-basic/src/App.js, React InstantSearch/routing-basic/src/index.js, React InstantSearch/routing-basic/yarn.lock
This updates the routing example in React InstantSearch:
- Uses hooks and functional components instead of classes
- Uses the latest version of the client
This change reflects the [documentation snippets](https://www.algolia.com/doc/guides/building-search-ui/going-further/routing-urls/react/#basic-urls) (minor changes to do there, will handle) and solve a [query duplication issue](https://github.com/algolia/react-instantsearch/issues/3187).
fixes https://github.com/algolia/react-instantsearch/issues/3187
=> feat(react-instantsearch): update routing basic example

Angular InstantSearch/algolia-insights/src/styles.css, Angular InstantSearch/autocomplete-results-page/src/styles.css, Angular InstantSearch/infinite-scroll/src/styles.css, Angular InstantSearch/multi-index-autocomplete/src/styles.css, Angular InstantSearch/multi-index-hits/src/styles.css, Angular InstantSearch/query-suggestions/angular.json, Angular InstantSearch/query-suggestions/src/styles.css, Angular InstantSearch/refresh/src/styles.css, Angular InstantSearch/routing-basic/src/styles.css, Angular InstantSearch/routing-seo-friendly/src/styles.css, Angular InstantSearch/routing-state-mapping/src/styles.css, Angular InstantSearch/secured-api-keys/src/styles.css
This PR addresses [this comment](https://github.com/algolia/doc-code-samples/pull/318#pullrequestreview-800364340), adding basic styles for Angular IS examples that display browser default styles.
=> fix(Angular IS): avoid default browser styling

React InstantSearch/routing-basic/src/App.js, React InstantSearch/routing-seo-friendly/src/App.js
This change fixes the behaviour of the back button in basic and SEO friendly routing example
Prior to this change, the examples were missing the bit that updates the externally managed `searchState` when `location` changes:
```jsx
const [searchState, setSearchState] = useState(urlToSearchState(location));
useEffect(() => {
setSearchState(urlToSearchState(location));
}, [location]);
```
fixes [FX-246](https://algolia.atlassian.net/browse/FX-246)
Related doc PR: https://github.com/algolia/doc/pull/6465
=> fix(React IS): fix back button behaviour with basic and seo friendly routing

React InstantSearch/injected-content/package.json, React InstantSearch/injected-content/src/App.css, React InstantSearch/injected-content/src/pages/Recommend.js, React InstantSearch/injected-content/src/routes.js, React InstantSearch/injected-content/yarn.lock
This adds a **Recommend** page to the injected-content code sample, that will be used to illustrate a new in-depth section in the [**Injecting content between hits**](https://github.com/algolia/doc/pull/6541) guide.
[**Preview →**](https://codesandbox.io/s/github/algolia/doc-code-samples/tree/feat/injected-content-recommend/React%20InstantSearch/injected-content?file=/src/pages/Recommend.js)
=> feat(React InstantSearch): add Recommend implementation in injected content sample

react-instantsearch-hooks-native/getting-started/src/SearchBox.tsx
This removes the `useEffect()`s from the `<SearchBox>` component in the React Native example.
- https://github.com/algolia/doc/pull/7189
=> fix(React Native): update `<SearchBox>` without Effects

Angular InstantSearch/getting-started/src/styles.css
Small PR to fix a style issue on this code sample, that users might encounter when looking at Angular InstantSearch's documentation.
**Before / After**
=> fix(getting-started): adjust styles

instantsearch.js/multi-index-hits/src/app.js
This has been changed a long time ago in https://www.algolia.com/doc/guides/building-search-ui/ui-and-ux-patterns/multi-index-search/js/, but for some reason never updated here
FX-1802
=> fix(js): correct sample for multi-index-hits

react-instantsearch-hooks/facet-dropdown/src/components/FacetDropdown.tsx
This PR implements `$$widgetType` to the `FacetDropdown` widget for RISH.
=> fix(metadata): implement `$$widgetType` for Facet Dropdown with RISH

instantsearch.js/facet-dropdown/src/Dropdown.js
This PR implements `$$widgetType` to the FacetDropdown widget for IS.js
=> fix(metadata): implement `$$widgetType` for Facet Dropdown with IS.js

vue-instantsearch/nuxt/package.json
Currently [the nuxt example does not work on CodeSandbox](https://codesandbox.io/s/github/algolia/doc-code-samples/tree/master/vue-instantsearch/nuxt), we get an error saying the container does not have enough available space.
Seems like just bumping the version of nuxt does the trick, it probably generates less stuff inside the `.nuxt` folder ?
[Branch preview on CodeSandbox](https://codesandbox.io/s/github/algolia/doc-code-samples/tree/fix/vue-nuxt-bump-dependency/vue-instantsearch/nuxt)
=> fix(nuxt): bump nuxt version to fix issue on CodeSandbox

instantsearch.js/facet-dropdown/index.html, instantsearch.js/facet-dropdown/src/Dropdown.js, instantsearch.js/facet-dropdown/src/app.js
This fixes an issue that was introduced by a change in InstantSearch.js in [v4.29.0](https://github.com/algolia/instantsearch.js/compare/v4.28.0...v4.29.0) (see [pull request](https://github.com/algolia/instantsearch/pull/4845)). On `init`, the panel's templates aren't rendered yet, so I'm now using `render` instead.
This demo could use a little bit of extra refactoring, but for the sake of legibility, I kept the changes as minimal as possible.
Related Jira ticket: https://algolia.atlassian.net/browse/CR-2851
fixes #422
=> fix(instantsearch.js/facet-dropdown): use render instead of init

instantsearch.js/facet-dropdown/src/Dropdown.js
In the case of `refinementList` for example, clicking on an item would always close the dropdown even if it is inside because they are always completely rebuilt instead of mutated ([key gets changed when refined](https://github.com/algolia/instantsearch/blob/c207de362a829f6bf44e1fe51e8a4e4a44d7d240/packages/instantsearch.js/src/components/RefinementList/RefinementList.tsx#L161C1-L167C6)), thus the `rootElem.contains(event.target)` condition would always return `false`.
By using `composedPath()` instead of relying on a DOM element that might disappear, this fixes the behavior observed in the issue.
[CR-4001]: https://algolia.atlassian.net/browse/CR-4001?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> fix(facet-dropdown): dropdown closes even if clicked inside
